---
- hosts: all
  vars_files:
    - roles/certs/vars/server-a.yml
  roles:
    - certs

- hosts: all
  vars_files:
    - roles/certs/vars/server-b.yml
  roles:
    - certs

- hosts: all
  vars_files:
    - roles/certs/vars/server-c.yml
  roles:
    - certs

